shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3

packages:
  - playground

overrides:
  zero-vue: 'link:.'
ignoredBuiltDependencies:
  - esbuild
  - protobufjs
  - unrs-resolver

onlyBuiltDependencies:
  - '@rocicorp/zero-sqlite3'
  - oxc-resolver
  - simple-git-hooks

allowBuilds:
  '@rocicorp/zero-sqlite3': true
  esbuild: true
  protobufjs: true
  simple-git-hooks: true
